### ISSUE TITLE
اصلاح اندازه ی فریم ها از iPhone 14 به Android Large

### ISSUE THREAD

**Issue by university-misaghi** [university-misaghi/CE-Project-1401-1402#10]

**Comment by SadraNafisi** [comment]
فریم های "تنظیمات حریم خصوصی" و "دیوار کاربر" اصلاح شد.

**Comment by university-misaghi** [comment]
من هم اصلاح کردم

**Comment by Masoumeh-Ostvar** [comment]
فریم های "اعلان ها" و "اخبار" اصلاح شد.

**Comment by Alireza8Ch1** [comment]
فریم ها رو منم اصلاح کردم و صفحه مربوط به اشتراک گذاری رویداد هم ایجاد کردم
